# Generated by Django 2.2 on 2019-04-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190420_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='customer',
            new_name='id_customer',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='lawyer',
            new_name='id_lawyer',
        ),
    ]
