# Generated by Django 2.2 on 2019-04-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190420_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_facebook_auth',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_google_auth',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='is_facebook_auth',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='is_google_auth',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
