# Generated by Django 2.2 on 2019-04-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190420_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='lawyer',
            old_name='user',
            new_name='id_user',
        ),
    ]
