# Generated by Django 2.2 on 2019-04-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190420_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='lawyer',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='id_customer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='id_lawyer',
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='api.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='lawyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to='api.Lawyer'),
        ),
    ]
