# Generated by Django 2.2 on 2019-04-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190420_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='api.Customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='lawyer',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to='api.Lawyer'),
        ),
    ]
