# Generated by Django 2.2 on 2019-04-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190420_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='lawyer',
        ),
    ]
